### ISSUE TITLE
use r-universe for installing nfidd

### ISSUE THREAD

**Issue by sbfnk** [nfidd/ueifid#35]
I just remembered an issue from running mfiidd before that with multiple people installing a package from github on the same WIFI within a short time frame one could quickly get 403 errors.

I've added nfidd to the epiforecasts r universe which should avoid this. Once this is built we can make the small change to the install instructions.

When doing this we can also switch to `install.packages()`, removing the need to install `pak`.

**Comment by seabbs** [comment]
Good catch. We might still want `pak` for dependency management (if any)

**Comment by sbfnk** [comment]
won't `install.packages()` also do that with `dependencies = TRUE` and the universe repos given? Perhaps `pak` does it better but I've also found it a bit unreliable.

**Comment by seabbs** [comment]
I mean non-R deps. I haven't really seen it be unreliable but I also don't feel strongly
